site_name: Saturn Docs
site_description: Documentation for Saturn Framework
site_author: Krzysztof Cieslak

# Repository
repo_name: SaturnFramework/docs
repo_url: https://github.com/SaturnFramework/docs

#Pages
pages:
  - Home: 'index.md'
  - Guides:
    - How to start in 60 seconds: 'guides/how-to-start.md'
  - Api Reference:
    - Pipeline: `api/pipeline.md`
    - Scope: 'api/scope.md'
    - Controller: 'api/controller.md'
    - Application: 'api/application.md'


#Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'blue'
    accent: 'teal'

#Social
extra:
  social:
    - type: 'github'
      link: 'https://github.com/SaturnFramework'
    - type: globe
      link: http://lambdafactory.io